// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdcCpywfMSUfsBjjX_DDm4MuU8q3Ym3kU',
    appId: '1:99517079861:web:08911b0093bdb8b6366c7c',
    messagingSenderId: '99517079861',
    projectId: 'sdsl-89bde',
    authDomain: 'sdsl-89bde.firebaseapp.com',
    storageBucket: 'sdsl-89bde.appspot.com',
    measurementId: 'G-SZG80BMF9H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALttd7PXXLfuCpgilAcqIiuTx-RelOTRM',
    appId: '1:99517079861:android:ad809cba6c0f944f366c7c',
    messagingSenderId: '99517079861',
    projectId: 'sdsl-89bde',
    storageBucket: 'sdsl-89bde.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDckO5teGfckGAQ7GIl0IdgQM2pl3aX8kc',
    appId: '1:99517079861:ios:16429cc70069537b366c7c',
    messagingSenderId: '99517079861',
    projectId: 'sdsl-89bde',
    storageBucket: 'sdsl-89bde.appspot.com',
    iosClientId: '99517079861-vi6pp1tlkp8hbvgpvoqredubh7jlf9lm.apps.googleusercontent.com',
    iosBundleId: 'com.example.sdsl',
  );
}
